### ISSUE TITLE
Help runtime 

### ISSUE THREAD

**Issue by simonbrd** [PengNi/deepsignal-plant#18]
Hello, I have been using your tool for a short time. I would like to have information on the average calculation time of this command:

`CUDA_VISIBLE_DEVICES=-1 deepsignal_plant call_mods --input_path /home1/scratch/sbrocard/DPALL/FAST5S --model_path /home1/scratch/sbrocard/DPALL/deepsignal-pl/model.dp2.CNN.arabnrice2-1_120m_R9.4plus_tem.
bn13_sn16.both_bilstm.epoch6.ckpt --result_file /home1/scratch/sbrocard/DPALL/deepsignal-pl/2_fast5s.C.call_mods.tsv --corrected_group RawGenomeCorrected_000 --motifs C --nproc 30 --reference_path /home/
datawork-lpba/Prymnesium/epigenetique/NANOPORE/1_run_nanopore/0_data/0_ref_genome/PrymneGenomeV1.fasta >& /home1/scratch/sbrocard/DPALL/deepsignal-pl/2_deepsignal-pl-call.log 2>&1
`
Knowing that in my .log file I have this:

`
input_path:
        /home1/scratch/sbrocard/DPALL/FAST5S
model_path:
        /home1/scratch/sbrocard/DPALL/deepsignal-pl/model.dp2.CNN.arabnrice2-1_120m_R9.4plus_tem.bn13_sn16.both_bilstm.epoch6.ckpt
model_type:
        both_bilstm
seq_len:
        13
signal_len:
        16
layernum1:
        3
layernum2:
        1
class_num:
        2
dropout_rate:
        0
n_vocab:
        16
n_embed:
        4
is_base:
        yes
is_signallen:
        yes
batch_size:
        512
hid_rnn:
        256
result_file:
        /home1/scratch/sbrocard/DPALL/deepsignal-pl/2_fast5s.C.call_mods.tsv
recursively:
        yes
corrected_group:
        RawGenomeCorrected_000
basecall_subgroup:
        BaseCalled_template
reference_path:
        /home/datawork-lpba/Prymnesium/epigenetique/NANOPORE/1_run_nanopore/0_data/0_ref_genome/PrymneGenomeV1.fasta
is_dna:
        yes
normalize_method:
        mad
motifs:
        C
mod_loc:
        0
f5_batch_size:
        10
region:
        None
positions:
        None
nproc:
        30
nproc_gpu:
        2
# ===============================================
[main] call_mods starts..
cuda availability: False
192615 fast5 files in total..
parse the motifs string..
read genome reference file..
`
Besides, if you know how to speed up the order, I'm interested, because my script has been running for 48 hours.

thank you in advance

**Comment by simonbrd** [comment]
My genome file is 109MB in size. I don't know why this one would be blocked?

**Comment by PengNi** [comment]
This is a small genome. It should not be a problem in reading. So it is weired that it didn't work. I suggest that you either try again, or use the latest version of deepsginal-plant (0.1.5) without setting the reference genome path.

Best,
Peng

**Comment by simonbrd** [comment]
Thank you have a good day.
