### ISSUE TITLE
pod5/slow5 support

### ISSUE THREAD

**Issue by PengNi** [PengNi/deepsignal-plant#22]
pod5: https://github.com/nanoporetech/pod5-file-format
slow5: https://github.com/hasindu2008/slow5lib

use tombo api to resquiggle (#5).

**Comment by PengNi** [comment]
May be also change to a mapping-free method - align signals to read sequence

**Comment by AlineMuyle** [comment]
Dear Dr Peng,
I was wondering if you are considering updating your deepsignal-plant pipeline with the new compressed pod5 format? Including the resquiggle step. That would be extremely useful because my fast5 files are very large.
Thank you for your help.
Best wishes

**Comment by PengNi** [comment]
move to [deepsignal3](https://github.com/PengNi/deepsignal3).
