### ISSUE TITLE
tombo resquiggle produces unexpected error

### ISSUE THREAD

**Issue by skranz0** [PengNi/deepsignal-plant#37]
I'm trying to use deepsignal-plant, however, after running the combo resquiggle command, I get the result that 99.9 % of my reads were unsuccessful due to an unexpected error. The produced error file says
```
BaseCalled_template:::../single_read_fast5/362/3811ae13-53be-4574-8239-b694ccc93228.fast5
:::
Traceback (most recent call last):
  File "/home/anfny/.conda/envs/tombo/lib/python3.6/site-packages/tombo/resquiggle.py", line 1404, in _io_and_map_read
    map_thr_buf, q_score_thresh, seq_len_rng)
  File "/home/anfny/.conda/envs/tombo/lib/python3.6/site-packages/tombo/resquiggle.py", line 1336, in map_read
    seq_data.id.decode(), bc_subgrp, num_start_clipped_bases,
AttributeError: 'str' object has no attribute 'decode'
```
for every read.

Is this a known issue and is there a way I can solve it?

**Comment by PengNi** [comment]
Hi @skranz0 , this maybe an installation issue. You can check the package versions in your environment match those in [setup.py of tombo](https://github.com/nanoporetech/tombo/blob/master/setup.py#L69), and re-install if necessary.

Another way you can try is that, directly modify line 1336 in this file "/home/anfny/.conda/envs/tombo/lib/python3.6/site-packages/tombo/resquiggle.py" by change `seq_data.id.decode()` to ` seq_data.id`.

Hope it helps.
Peng

**Comment by skranz0** [comment]
This actually worked! Still none of my reads were processed successfully, but that's another issue. Since it's deprecated, tombo will probably not correct this
