### ISSUE TITLE
Use multiple GPU at the same time

### ISSUE THREAD

**Issue by sengelen** [PengNi/deepsignal-plant#38]
Hi PengNi,

Thanks for providing the nice tool.
I was wondering if Deepsignal-plant could use multiple GPU at the same time ? I set CUDA_VISIBLE_DEVICES to 2,3 in order to use multiple GPU at same time but deepsignal-plant dispatches calling process only on one GPU (allways the visible GPU with the smallest id)  

Thank you for your help.
Best wishes

**Comment by PengNi** [comment]
Hi @sengelen , thanks very much for using our tool. I am not sure, but maybe the visible GPU is the only GPU you are authorized to use in your system? CUDA_VISIBLE_DEVICES can be only set to the GPUs you can use.

Best,
Peng

**Comment by sengelen** [comment]
No I can use all the GPU of the node and all (in fact four) are visible but deepsignal-plant only used one of these GPU. Is there an option in deepsignal-plant to use more than one GPU ?

**Comment by PengNi** [comment]
Hi @sengelen , 
1. did you process the reads with Tombo before the `call_mods` step? How did the log of `tombo resquiggle` say?
2. It may due to the vbz issue, please try the following before the `call_mods` step:
```sh
# download ont-vbz-hdf-plugin-1.0.1-Linux-x86_64.tar.gz (or newer version) and set HDF5_PLUGIN_PATH
# https://github.com/nanoporetech/vbz_compression/releases
wget https://github.com/nanoporetech/vbz_compression/releases/download/v1.0.1/ont-vbz-hdf-plugin-1.0.1-Linux-x86_64.tar.gz
tar zxvf ont-vbz-hdf-plugin-1.0.1-Linux-x86_64.tar.gz
export HDF5_PLUGIN_PATH=/abslolute/path/to/ont-vbz-hdf-plugin-1.0.1-Linux/usr/local/hdf5/lib/plugin
```

Best,
Peng

**Comment by sengelen** [comment]
Hi Peng
I think after building many Docker images I lose the part related to the vbz issue. Now all the GPU are used so it works well !!!
Many thanks
Stefan
