### ISSUE TITLE
tombo preprocess annotate_raw_with_fastqs

### ISSUE THREAD

**Issue by olmath** [PengNi/deepsignal-plant#7]
Hi,

when trying to run `tombo preprocess annotate_raw_with_fastqs`, I am getting the following  error:

$ tombo preprocess annotate_raw_with_fastqs --fast5-basedir fast5_pass/ --fastq-filenames fastq_pass/ --basecall-group Basecall_1D_000 --basecall-subgroup BaseCalled_template --overwrite --processes 10
[10:28:36] Preparing reads and extracting read identifiers.
0it [00:00, ?it/s]
[10:28:36] Annotating FAST5s with sequence from FASTQs.
****** WARNING ****** Some FASTQ records contain read identifiers not found in any FAST5 files or sequencing summary files.
0it [00:00, ?it/s]
[10:28:36] Added sequences to a total of 0 reads.

I have tried using single paired fast5/fastq files as input and got the same error. 
I have also verified that fast5 files are writable.

Can you help with this issue?
Many thanks

**Comment by PengNi** [comment]
Hi @olmath , may be the issue is that the value of `--fastq-filenames` can only be a file rather than a directory.

Try the following commands:
```sh
cat fastq_pass/*.fastq > fastq_pass.fastq
tombo preprocess annotate_raw_with_fastqs --fast5-basedir fast5_pass/ \ 
    --fastq-filenames fastq_pass.fastq --basecall-group Basecall_1D_000 \
    --basecall-subgroup BaseCalled_template --overwrite --processes 10
```

Best,
Peng

**Comment by olmath** [comment]
Thanks Peng.

I have tried and got the same error:

```
$ tombo preprocess annotate_raw_with_fastqs --fast5-basedir fast5_pass/ --fastq-filenames fastq_pass.fastq --basecall-group Basecall_1D_000 --basecall-subgroup BaseCalled_template --overwrite --processes 10
[10:50:36] Preparing reads and extracting read identifiers.
0it [00:00, ?it/s]
[10:28:36] Annotating FAST5s with sequence from FASTQs.
****** WARNING ****** Some FASTQ records contain read identifiers not found in any FAST5 files or sequencing summary files.
0it [00:00, ?it/s]
[10:50:36] Added sequences to a total of 0 reads.
```

**Comment by PengNi** [comment]
@olmath , it is weird that this does not work. I suggest that you re-basecall the fast5s using Guppy and use the newly basecalled fastq to have a another try.

Or if it is possible, you can share me one or two fast5s, so I can test too.

Best,
Peng

**Comment by olmath** [comment]
Thank you Peng.
I will try. How can I share fast5 files with you?

**Comment by PengNi** [comment]
@olmath , you can attach files by dragging & dropping within a reply, or share using google drive.

Best,
Peng

**Comment by olmath** [comment]
Thanks Peng. Here are two of my fast5 files:
https://drive.google.com/drive/folders/1bxL7FCyr5gzcTQ41dRd_kvkYkHGgsZvQ?usp=sharing

**Comment by PengNi** [comment]
Hi @olmath , I tested the two fast5s you shared, and tombo worked well.

I re-basecalled the two fast5s first using Guppy, and then use `tombo preprocess annotate_raw_with_fastqs` as follows:
```sh
tombo preprocess annotate_raw_with_fastqs --fast5-basedir test --fastq-filenames test_fq/fastq_runid_e7751becc2e46db2e98d4d07adc55dc9b602d094_0_0.fastq --basecall-group Basecall_1D_000 --basecall-subgroup BaseCalled_template --overwrite --processes 10
```
The log is:
```sh
[09:50:31] Preparing reads and extracting read identifiers.
/home/nipeng/tools/tomboenv/lib/python3.5/site-packages/tombo/_preprocess.py:378: H5pyDeprecationWarning: The default file mode will change to 'r' (read-only) in h5py 3.0. To suppress this warning, pass the mode you need to h5py.File(), or set the global default h5.get_config().default_file_mode, or set the environment variable H5PY_DEFAULT_READONLY=1. Available modes are: 'r', 'r+', 'w', 'w-'/'x', 'a'. See the docs for details.
  with h5py.File(fast5_fn) as fast5_data:
/home/nipeng/tools/tomboenv/lib/python3.5/site-packages/tombo/_preprocess.py:378: H5pyDeprecationWarning: The default file mode will change to 'r' (read-only) in h5py 3.0. To suppress this warning, pass the mode you need to h5py.File(), or set the global default h5.get_config().default_file_mode, or set the environment variable H5PY_DEFAULT_READONLY=1. Available modes are: 'r', 'r+', 'w', 'w-'/'x', 'a'. See the docs for details.
  with h5py.File(fast5_fn) as fast5_data:
 50%|██████████████████████████████████████████████████████████████████████████████████████████████▌                             100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:00<00:00,  6.59it/s]
[09:50:31] Annotating FAST5s with sequence from FASTQs.
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████]████████████████████████████████████████████████████████████████████████████████| 2/2 [00:00<00:00, 19.73it/s]
[09:50:32] Added sequences to a total of 2 reads.
```

I note that the fast5s already have basecalled fastqs. Maybe the fastq in fast5s and the fastq in your fastq files are the same, which makes tombo think the fast5s don't need to be overwrited. Just a guess.
![image](https://user-images.githubusercontent.com/4242364/120734369-56718080-c51b-11eb-8964-07c6f95ffacd.png)



Best,
Peng

**Comment by olmath** [comment]
Thank you Peng.
Would you mind letting me know what parameters you're passing to Guppy for the basecalling?
I have re-performed basecalling and I get the same error...

**Comment by PengNi** [comment]
Hi @olmath , I used the default parameters:
```sh
guppy_basecaller -i test -r -s test_fq --config dna_r9.4.1_450bps_hac_prom.cfg --device CUDA:0
```

Best,
Peng

**Comment by olmath** [comment]
I am basecalling on CPU, could it be the issue?
`~/ont-guppy-cpu/bin/guppy_basecaller -i test_fast5_single/ -r -s test_fq --config dna_r9.4.1_450bps_fast.cfg --num_callers 4  --cpu_threads_per_caller 5`

**Comment by PengNi** [comment]
@olmath , I don't think CPU/GPU is the issue. It is really weird. May be we should check if tombo is installed properly, and test more data.

**Comment by olmath** [comment]
You mentioned that the fast5s that I shared with you already have basecalled fastqs. Is it similar when you re-bascalled these fast5s on your side? Is that an option in Guppy that I can turn off?

If I run tombo resquiggle directly on the fast5 files I shared with you, it seems to be working properly:
```
$ tombo resquiggle test_fast5_single/ ~/database/Arabidopsis_thaliana/TAIR10/TAIR10.fa --processes 20 --corrected-group RawGenomeCorrected_000 --basecall-group Basecall_1D_000 --overwrite
[15:58:49] Loading minimap2 reference.
[15:58:57] Getting file list.
[15:58:57] Loading default canonical ***** DNA ***** model.
[15:58:58] Re-squiggling reads (raw signal to genomic sequence alignment).
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.99it/s]
[15:58:59] All reads successfully re-squiggled!
[15:58:59] Saving Tombo reads index to file.
```

**Comment by PengNi** [comment]
> You mentioned that the fast5s that I shared with you already have basecalled fastqs. Is it similar when you re-bascalled these fast5s on your side? Is that an option in Guppy that I can turn off?
> 
> If I run tombo resquiggle directly on the fast5 files I shared with you, it seems to be working properly:
> 
> ```
> $ tombo resquiggle test_fast5_single/ ~/database/Arabidopsis_thaliana/TAIR10/TAIR10.fa --processes 20 --corrected-group RawGenomeCorrected_000 --basecall-group Basecall_1D_000 --overwrite
> [15:58:49] Loading minimap2 reference.
> [15:58:57] Getting file list.
> [15:58:57] Loading default canonical ***** DNA ***** model.
> [15:58:58] Re-squiggling reads (raw signal to genomic sequence alignment).
> 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.99it/s]
> [15:58:59] All reads successfully re-squiggled!
> [15:58:59] Saving Tombo reads index to file.
> ```

- you can check your fast5s by the tool HDF-view. The 2 fast5s I tested have both basecall and resquiggle results. 
- This has nothing to do with Guppy, cause Guppy does not change (write) the input fast5s.

Best,
Peng

**Comment by olmath** [comment]
Hi @PengNi, re-installing a new environment solved the issue, so I guess an incorrect installation of tombo was likely the cause of my problem.
Many thanks for your help.

**Comment by PengNi** [comment]
@olmath , it is a pleasure.

Best,
Peng
